apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-prod
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/gcp-101-405620/emp-app/employee-app
